# Database configuration for Quarkus application
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=autoflex
quarkus.datasource.password=autoflex123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/autoflex_db

# Flyway configuration for migrations
quarkus.flyway.migrate-at-start=true

# Hibernate configuration
# Disable Hibernate automatic generation to use flyway
quarkus.hibernate-orm.database.generation=none